apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hello
spec:
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: =
      values:
      - hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: us-docker.pkg.dev/google-samples/containers/gke/whereami@sha256:9957f5ff3096a83bae4e0952faaebcac740557e7fb2a642ed38bf5cb64c45795
        name: hello
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
status: {}

